name: D:\ProgramData\miniconda3\envs\cove
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=1.1.1w=h2bbff1b_0
  - pip=25.2=pyhc872135_1
  - python=3.10.0=h96c0403_3
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - datasets==4.3.0
      - dill==0.4.0
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - idna==3.11
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.25
      - langchain-community==0.3.7
      - langchain-core==0.3.67
      - langchain-ollama==0.3.0
      - langchain-text-splitters==0.3.8
      - langgraph==1.0.1
      - langgraph-checkpoint==3.0.0
      - langgraph-prebuilt==1.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.38
      - marshmallow==3.26.1
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - numpy==1.26.4
      - ollama==0.6.0
      - orjson==3.11.4
      - ormsgpack==1.11.0
      - packaging==24.2
      - pandas==2.3.3
      - propcache==0.4.1
      - pyarrow==22.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.35
      - tenacity==9.1.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: D:\ProgramData\miniconda3\envs\cove
